### ISSUE TITLE
PARLA 1 - NOVA matéria 3

### ISSUE THREAD

**Issue by dtiriba** [alerj/parla#104]
titulo
Sindalerj recebe servidores comissionados

ordem
3

categoria / editoria
Sindalerj

subtitulo
NÃO TERÁ

lead
Todo servidor comissionado e requisitado a partir de agora pode se filiar ao Sindicato dos Servidores da Alerj - Sindalerj. Com uma contribuição mensal de apenas R$ 20, o sindicato, que antes aceitava apenas integrantes concursados, oferece convênios e diversos serviços aos seus novos associados, assim como aos 700 servidores ativos, aposentados e familiares. Na próxima semana o presidente da entidade, Nelson Braga Moreno, dará início à campanha interna e visitará os setores para falar sobre as vantagens e benefícios da adesão.

texto
"Estamos anunciando um desconto na contribuição, que era de R$ 35 reais, para motivar novos associados", afirmou Moreno. Segundo ele, a entrada dos comissionados ainda está tímida, mas ele espera alcançar mais adeptos quando todos tiverem acesso à pauta de reivindicações para 2018/2019. A realização de um concurso público para os diversos setores da Casa faz parte da lista.
 
 "Somos poucos servidores na ativa e muitos às vésperas da aposentadoria. Precisamos renovar nossos quadros", disse Moreno, que enumerou como prioridades o ajuste no auxílio-alimentação (já concedido);  a criação do auxílio-saúde e o novo plano de cargos e salários.
 
"Lutamos por todos, seja estatutário ou não. O importante é que aqueles que trabalham na Alerj sejam comissionados ou requisitados, se sintam representados dentro das normas legais. Ser sindicalizado é se fazer ouvir",  destacou o presidente.
 
**Filiação e benefícios**
O cadastro deve ser feito através do preenchimento de uma ficha de inscrição na sede do sindicato, na [Travessa do Paço, 23](https://goo.gl/maps/UDBEzWYviKr) - Sala 205, Centro, ao lado do Palácio Tiradentes. Mais informações podem ser obtidas pelo telefones 2253-0435 e 2203-0415 ou pelo e-mail: [sindalerj@sindalerj.com.br](sindalerj@sindalerj.com.br). 
 
Os associados do Sindalerj contam com os benefícios exclusivos por meio das parcerias com planos de saúde, faculdades, restaurantes, farmácias e agências de viagem. Dispõem também de assistência jurídica e serviço contábil.

autores
Symone Munay 

tags
sindalerj, servidores, sindicato,

**Comment by brenot** [comment]
Não temos imagens?
@dtiriba

**Comment by brenot** [comment]
@dtiriba Essa imagem ai não ta legal nao... :( não tem ele com uma resolução melhor?

**Comment by brenot** [comment]
@dtiriba  Além de estar fora do padrão (formato) combinado ;)

**Comment by brenot** [comment]
@dtiriba eu nao alterei a proporção não...

Ela tá ligeiramente fora, como você pode observar na pagina, na lista, onde ele aparece ao lado das outras..  Vou corrigir esta, mas pro futuro é muito importante estar atento a isto, pois nem sempre poderemos arrumar aqui.

**Comment by dtiriba** [comment]
Perdão, @brenot . Percebi agora que te mandei o arquivo errado. Eu salvei com outro nome depois de fazer o corte, mas mandei o outro.
