### ISSUE TITLE
Alteração rodapé

### ISSUE THREAD

**Issue by tainahvieiracj** [alerj/parla#108]
Alterar o expediente (no rodapé da página) para:

Jornalista responsável: Celia Abend
Editor: André Coelho
Coordenação: Daniela Matta e Jorge Ramos
Equipe: Buanna Rosa, Camilla Pontes, Gherson Murillo, Gustavo Natario, Hélio Lopes, Isabela Cabral, Leon Lucius, Octacílio Barbosa, Tainah Vieira, Thiago Lontra (foto), Symone Munay, Vanessa Schumacker e Wagner da Silva
Edição de Arte: Daniel Tiriba
Editor de Fotografia: Rafael Wallace
Secretária da Redação: Regina Torres
Estagiários: Audryn Karolyne, David Barbosa, Julia Passos (redes sociais), Luan Damasceno, Luís Gustavo (foto)

**Comment by antonioribeiro** [comment]
Done by @brenot

**Comment by brenot** [comment]
@tainahvieiracj  @antonioribeiro  Feito

**Comment by antonioribeiro** [comment]
Já dei merge: https://parla.antoniocarlosribeiro.com/
