### ISSUE TITLE
Texto principal da matéria da Elerj

### ISSUE THREAD

**Issue by tainahvieiracj** [alerj/parla#110]
Trocar o texto que aparece na home sobre a matéria da Elerj para o seguinte:

A primeira turma da pós graduação totalmente organizada pela Escola do Legislativo do Estado do Rio de Janeiro (Elerj) termina o curso em outubro. Autorizada pelo Conselho Estadual de Educação (CEE-RJ) em maio de 2017, a pós de Gestão no Poder Legislativo conta com 44 alunos e, segundo a diretora a Elerj, Rosemery Borges, a criação de novas turmas já está nos planos para o próximo ano. Antes dessa turma, outros cursos de especialização já haviam sido realizados, mas sempre em parceria com instituições de ensino.

**Comment by antonioribeiro** [comment]
Isso é novo lead da matéria, certo?

**Comment by tainahvieiracj** [comment]
Sim

**Comment by antonioribeiro** [comment]
Done.
