### ISSUE TITLE
Alteração no rodapé

### ISSUE THREAD

**Issue by tainahvieiracj** [alerj/parla#114]
Incluir "(foto)" ao lado de "Octacílio Barbosa", que está na lista da equipe.

Fica assim:

Jornalista responsável: Celia Abend
Editor: André Coelho
Coordenação: Daniela Matta e Jorge Ramos
Equipe: Buanna Rosa, Camilla Pontes, Gherson Murillo, Gustavo Natario, Hélio Lopes, Isabela Cabral, Leon Lucius, Octacílio Barbosa (foto), Tainah Vieira, Thiago Lontra (foto), Symone Munay, Vanessa Schumacker e Wagner da Silva
Edição de Arte: Daniel Tiriba
Editor de Fotografia: Rafael Wallace
Secretária da Redação: Regina Torres
Estagiários: Audryn Karolyne, David Barbosa, Julia Passos (redes sociais), Luan Damasceno, Luís Gustavo (foto)

**Comment by antonioribeiro** [comment]
Done.

**Comment by tainahvieiracj** [comment]
ok! tks
