### ISSUE TITLE
Correção matéria Elerj

### ISSUE THREAD

**Issue by tainahvieiracj** [alerj/parla#116]
Corrigir na matéria da Elerj:

Incluir uma aspa no começo do 2º parágrafo. 
Fica assim:

"A qualificação é primordial para o Legislativo e queremos que esse projeto permaneça. Inclusive, demos entrada no Ministério de Educação (MEC), no mês de maio, solicitando autorização para a implementação do mestrado na Elerj. Um passo importante para a nossa Casa e para os funcionários que trabalham aqui”, afirmou Rosemery.

**Comment by antonioribeiro** [comment]
Done

**Comment by tainahvieiracj** [comment]
ok! tks
