### ISSUE TITLE
Alteração na matéria "Solidariedade através do esporte"

### ISSUE THREAD

**Issue by tainahvieiracj** [alerj/parla#119]
Trocar o primeiro parágrafo da matéria para:

Ele sempre foi irrequieto, alto, e gostava de desafios. Por isso, não foi difícil perceber que aquele adolescente, então com 14 anos, tinha o biótipo e a personalidade ideais para as artes marciais. E foi a partir do convite de um amigo que Elton Moura, hoje com 34 anos, 1,80 m de altura, e 98 kg; entrou no mundo dos golpes, tatames, quimonos e faixas. E dele não saiu mais. “Na primeira aula já me identifiquei com o jiu-jitsu e, com dois meses de treino, já competia”, lembra Elton, cinegrafista da Assembleia Legislativa do Rio de Janeiro (Alerj).

**Comment by antonioribeiro** [comment]
Done

**Comment by tainahvieiracj** [comment]
Boa! Pode subir pro site! Obrigada! Bjs
