### ISSUE TITLE
Primeira rodada de modificações

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/parla#12]
Solicitações feitas por Daniel Tiriba e e Daniela Matta:

- [X] É possível colocar a versão quadrada da logo (sem cúpula) como fav icon?

- [X] Parla nº 1 - Fevereiro 2018

- [X] Deixar as datas das matérias sem o zero. Ex: 8 de fevereiro de 2018. Ou, melhor, só com mês e ano.

- [X] Colocar o crédito da foto após as legendas que a Dani Matta vai enviar, entre parênteses. Ex: (Foto: Rafael Wallace) ou (Foto: Alexandre Madeira / Divulgação CCBB)

- [x] Aumentar logo em 20% e mudar título para Open Sans Extra Bold, dobrando o tamanho. Mudar fundo das tags para cinza claro.

- [X] Remover categorias

- [X] O nome da Celia Abend, por exemplo, não tem acento. Ele está no expediente.

- [X] Na matéria sobre os personagens do Carnaval, a palavra Carnaval deve vir sempre com o C maiúsculo.  (Nota Antonio Carlos: as tags que são todas em minúsculas mesmo.)

- [X] Legendas matérias 1 e 2

- [X] Matéria sobre exposição Ex Africa - No título, a palavra Centro precisa vir com o C maiúsculo.

- [X] Legendas

- [X] Matéria "Onde solucionar o seu problema" está com a foto errada

- [X] Matéria sobre o passado do Palácio

- [x] Alterar a data da matéria para mês/ano

- [x] A legenda da foto só precisa aparecer na parte de dentro (Daniel por WhatsApp)

**Comment by dtiriba** [comment]
Sobre a data da matéria, melhor deixar só mês e ano, mesmo.

**Comment by antonioribeiro** [comment]
Daniel, os créditos do fotógrafo na capa ficarão como?

1) (Foto: Raphael Wallace)

2) Foto: Raphael Wallace

**Comment by dtiriba** [comment]
(Foto: Rafael Wallace)

**Comment by antonioribeiro** [comment]
Todos os itens aqui foram fechados, os que não estão fechados, acho que nem aqui estão na verdade, então estou abrindo issues pra eles.
