### ISSUE TITLE
Expediente

### ISSUE THREAD

**Issue by dtiriba** [alerj/parla#121]
Favor incluir o nome da Márcia Manga no expediente. 

Fica assim:

Equipe: Buanna Rosa, Camilla Pontes, Gherson Murillo, Gustavo Natario, Hélio Lopes, Isabela Cabral, Leon Lucius, Márcia Manga, Octacílio Barbosa (foto), Tainah Vieira, Thiago Lontra (foto), Symone Munay, Vanessa Schumacker e Wagner da Silva

**Comment by antonioribeiro** [comment]
Foi feito mais cedo.
