### ISSUE TITLE
Datas das matérias

### ISSUE THREAD

**Issue by dtiriba** [alerj/parla#13]
Deixar as matérias sem data, uma vez que estão associadas à edição do mês.

No futuro, quando tivermos mais edições, podemos colocar um indicativo da edição a que pertence para não causar confusão.

**Comment by brenot** [comment]
MARAVILHA

**Comment by antonioribeiro** [comment]
Então na visualização da matéria também?

![image](https://user-images.githubusercontent.com/3182864/36396315-2f06fbe2-159c-11e8-9741-d80c5c99605e.png)

**Comment by dtiriba** [comment]
Por ora, sim. 

Autores da matéria vêm acima do primeiro parágrafo.

Vamos mandar conteúdo para o menu fixo (expediente e fale conosco).

**Comment by antonioribeiro** [comment]
Feito, mas isso

> Autores da matéria vêm acima do primeiro parágrafo.

É assunto para outra issue:

https://github.com/alerj/parla/issues/18
