### ISSUE TITLE
Data da edição

### ISSUE THREAD

**Issue by dtiriba** [alerj/parla#14]
Esqueci do "de". A data seria 

**Parla nº 1 - Fevereiro de 2018**

**Comment by brenot** [comment]
Ok

Alterei - https://github.com/alerj/parla/commit/ca710419323fab557ab516a8bad64399fe2e47d4

Antonio vai subir na sequencia

**Comment by antonioribeiro** [comment]
Parla 1 ou Parla 0?

**Comment by antonioribeiro** [comment]
@dtiriba Lembro que você falou algo sobre isso no WhatsApp hoje

**Comment by dtiriba** [comment]
Parla 0. 

Este é o piloto

**Comment by antonioribeiro** [comment]
Feito.
