### ISSUE TITLE
Matérias sem foto

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/parla#17]
Como será o tratamento disso, vai poder ficar sem foto?

Atualmente colocamos um "placeholder" na matéria "Onde solucionar o seu problema". Assim está bom ou vai ter foto?

**Comment by dtiriba** [comment]
Vou providenciar uma imagem ilustrativa para amanhã

**Comment by dtiriba** [comment]
![1044](https://user-images.githubusercontent.com/36640733/36437081-ce7e47fe-1644-11e8-8ee0-d7f56698c15f.jpg)

**Comment by dtiriba** [comment]
Imagem sem crédito nem legenda.

**Comment by antonioribeiro** [comment]
Feito
