### ISSUE TITLE
Design de título, subtítulo e corpo de matérias

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/parla#20]
Foi pedido para ser algo mais parecido com o que é o Medium, mas o @brenot está fazendo estudo de fontes para ficar bom.

**Comment by dtiriba** [comment]
Na verdade, parecido com o Medium só o tamanho e a entrelinha. 
As fontes podem ser as que indiquei mesmo

**Comment by antonioribeiro** [comment]
Estamos dando como ok este item.

**Comment by dtiriba** [comment]
Não. 

Abriremos novas issues com relação a isso.

**Comment by antonioribeiro** [comment]
Ok, fechando então.
