### ISSUE TITLE
Caracteres no destaque

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/parla#25]
@dtiriba, você pediu para colocar 200 chars no máximo em tudo, mas o Breno disse que no destaque está ficando ruim, podemos mudar isso?

**Comment by brenot** [comment]
Naquela primeira notica em destaque (que estaria dentro do slider) nós temos "espaço sobrando", não me faz sentido "esconder" (limitar) a introdução  como ta agora... Acho que podemos "liberar" mais caracteres somente nessa, pra poder preencher o espaço vazio e compor o layout.

![parla_swiper2](https://user-images.githubusercontent.com/1885417/36429155-a69c6ebe-1630-11e8-8f46-300757330343.png)

**Comment by dtiriba** [comment]
Acho que pode aumentar em caráter de teste para avaliarmos.

Mas o ideal seria colocar a foto do destaque principal numa proporção diferente, mais horizontalizada e ocupando duas colunas. É possível?

**Comment by antonioribeiro** [comment]
Já foi feito, verifique, por favor.

**Comment by antonioribeiro** [comment]
Alterado, mas o @brenot ainda vai fazer algumas modificações visuais.

**Comment by antonioribeiro** [comment]
Tudo resolvido, @dtiriba, favor verificar

**Comment by dtiriba** [comment]
Gostei muito! Vou mostrar aqui.

**Comment by dtiriba** [comment]
Aprovado!
