### ISSUE TITLE
Aumentar largura da imagem de destaque principal

### ISSUE THREAD

**Issue by dtiriba** [alerj/parla#33]
Aumentar aspect ratio da imagem de maneira que ela ocupe duas colunas e o texto de chamada fique na coluna da direita

![largura-imagem-destaque](https://user-images.githubusercontent.com/36640733/36437861-fdae691c-1646-11e8-8f66-7de1d22c561f.png)

**Comment by antonioribeiro** [comment]
Lembrando que não aumenta apenas a largura, a altura vai junto, empurrando todo o restante pra baixo e pro lado, mas vamos fazer

**Comment by antonioribeiro** [comment]
Nos nossos monitores, na média, vai aparecer assim

![image](https://user-images.githubusercontent.com/3182864/36438360-72dfdb52-1648-11e8-8cd6-f0e525e6e6ff.png)

Seria interessante que o usuário visse que tem conteúdo mais pra baixo, pode correr o risco do usuário achar que este é todo o conteúdo da página.

**Comment by antonioribeiro** [comment]
Feito
