### ISSUE TITLE
Matérias - título e subtítulo

### ISSUE THREAD

**Issue by dtiriba** [alerj/parla#39]
Mudar para OPEN SANS EXTRABOLD, cor #172a52

Mudar subtítulo. Aumentar a fonte de 22 para 26px.    `font-size: 26px;`

![materias-titulo](https://user-images.githubusercontent.com/36640733/36439549-10de3aa8-164c-11e8-8b1f-edf320fb901f.png)

**Comment by brenot** [comment]
ok
