### ISSUE TITLE
Matérias - imagens menores

### ISSUE THREAD

**Issue by dtiriba** [alerj/parla#42]
Alinhar legendas ao centro (ou à esquerda, se preferirem)

![materias-imagens-rodape](https://user-images.githubusercontent.com/36640733/36439948-2cc16bd6-164d-11e8-9e4a-a34c3168ca99.png)

**Comment by antonioribeiro** [comment]
Incluir opção de ampliar as imagens: vou abrir uma outra issue pra isso, porque não será feito agora.

**Comment by antonioribeiro** [comment]
Já havia sido feito: o alinhamento feito nas imagens maiores também modificou as menores.
