### ISSUE TITLE
Matérias - Leia também

### ISSUE THREAD

**Issue by dtiriba** [alerj/parla#48]
Incluir boxes para outras matérias no fim de cada matéria

**Comment by antonioribeiro** [comment]
Não está mais publicada.

**Comment by brenot** [comment]
Estou mandando a estrutura agora

@dtiriba  confirma pra mim se vai existir um titulo: 
Leia Também

**Comment by antonioribeiro** [comment]
feito

**Comment by dtiriba** [comment]
Acho legal ter. pequeno, em caixa alta, acima da linha. 

E acho tb que as matérias da parte de baixo podem vir menores. De repente com a imagem ao lado do texto

**Comment by brenot** [comment]
@dtiriba 
Tem como fazer um layout pra me mostrar mais precisamente como vc está pensando?

**Comment by dtiriba** [comment]
Seguem duas sugestões

![leia tambem](https://user-images.githubusercontent.com/36640733/36609348-59dca436-18ab-11e8-8299-baf763af21fa.jpg)

**Comment by dtiriba** [comment]
Não achei a opção de mexer em labels. Queira tirar o **waiting project owner**

**Comment by brenot** [comment]
https://github.com/alerj/parla/pull/69

Fiz uma mistura das duas da uma olhada depois por favor

**Comment by dtiriba** [comment]
Tá aparecendo igual para mim. Já dei crtl F5 e nada

**Comment by antonioribeiro** [comment]
@dtiriba , pode ver novamente? 

Fiz uma alteração no sistema para não ter mais que ficar dando CTRL+F5.

**Comment by dtiriba** [comment]
Está bacana!

**Comment by brenot** [comment]
Beleza então
