### ISSUE TITLE
Divisão de colunas da capa

### ISSUE THREAD

**Issue by dtiriba** [alerj/parla#49]
É possível dar a opção de dividirmos as matérias da capa, abaixo do destaque, em duas ou três colunas, de acordo com a melhor divisão da edição?

No caso desta edição, acho que seria mais adequado dividir em duas, para ficar dois blocos de duas.

**Comment by antonioribeiro** [comment]
Sim. Tá feito e vamos poder configurar por edição depois.

@brenot, acho que vai ter que dar uma olhada porque estranhei visualmente como ficou agora, mas podem ser meus olhos.

**Comment by antonioribeiro** [comment]
@dtiriba a ultima foto que você mandou está na proporção errada

![image](https://user-images.githubusercontent.com/3182864/36485866-f0eb4a46-16fb-11e8-8cc3-805a41bc8e05.png)

**Comment by brenot** [comment]
@dtiriba e @antonioribeiro 

O Antônio já mudou pra 2 colunas, pura e simplesmente. 

O que acho que precisamos fazer,  (até ja tinha comentado com o Antonio, quando eu tava fazendo a analise do Medium) pelo menos nesse primeiro momento que temos poucas materias, é:

- Colocar somente 2 colunas, mas não ocupando todo o espaço possível (as 12 colunas)
(da maneira de questa agora, a divisão é 6 e 6 , e com isso fica tudo grandão); a proposta é aumentar as áreas de respiro deixando no minimo uma coluna de cada lado vazia. 

Vou fazer as alterações e mando

**Comment by antonioribeiro** [comment]
Daniel, como você viu, dá pra fazer, mas não ficou bom, pra ficar provavelmente teremos que alterar o layout, mas não vai dar para ter 2 layouts diferentes, então temos definir um layout que sirva para as três condições: uma (mobile), duas e três colunas.

**Comment by dtiriba** [comment]
Estou tentando acessar para ver, mas o site não carrega.

**Comment by antonioribeiro** [comment]
É cache. Dá um CTRL+F5.

**Comment by dtiriba** [comment]
A questão é que, sendo feito em edições, o número de matérias é sempre limitado. Esta página inicial terá sempre de 4 a 7 matérias, mais ou menos.

Se forem 4, preenche legal. Se forem 7, tb. Se forem 5 matérias, como a atual, fica com só uma na segunda linha de matérias.

**Comment by antonioribeiro** [comment]
Não tenho problema em ter duas e três colunas, mas precisamos chegar num layout único que funcione para ambas.

Ter layouts diferentes significa ficar dando manutenção em dois, testar dois, toda vez que mudar um o outro vai ter que mudar também, ou não, e aí vão começar a surgir divergências visuais, que vão gerar mais mudanças, ladeira abaixo, ou "down the rabbit hole".

**Comment by dtiriba** [comment]
Entendi. Vou conversar aqui para chegar a uma solução editorial e aviso se preferimos com duas ou três

**Comment by dtiriba** [comment]
Vamos deixar com três colunas.
