### ISSUE TITLE
Capa - altura das chamadas

### ISSUE THREAD

**Issue by dtiriba** [alerj/parla#50]
É possível delimitar o tamanho da chamada pela altura em pixels e não pelos caracteres?

Digo isso pq, quando o título for menor que duas linhas, fica desparagonado com as outras 

![capa-chamadas](https://user-images.githubusercontent.com/36640733/36446556-6fa6214a-1660-11e8-91b4-a6d135b9fa6c.png)

**Comment by brenot** [comment]
https://github.com/alerj/parla/pull/53

**Comment by brenot** [comment]
https://github.com/alerj/parla/pull/53

**Comment by dtiriba** [comment]
O que foi feito aqui, na verdade, não foi ajustar o tamanho pela altura em pixels, mas definir um espaço fixo para o título, independente da quantidade de caracteres, certo?

Desse jeito ficou estranho. Se não der para fazer do jeito que falei, vou pensar em uma solução editorial
