### ISSUE TITLE
Margem na capa

### ISSUE THREAD

**Issue by dtiriba** [alerj/parla#63]
Diminuir a margem entre título e texto de introdução da matéria.

Manter a mesma que está para o botão LEIA MAIS (ou um pouco maior)

**Comment by brenot** [comment]
https://github.com/alerj/parla/pull/66

**Comment by brenot** [comment]
foi uma questão da responsividade, agora já ta bom, ou pelo menos ta melhor.... Quando acabarmos os ajustes de layout, precisarei fazer uma revisão em todos os viewports
