### ISSUE TITLE
Chamadas - imagem do restaurante

### ISSUE THREAD

**Issue by dtiriba** [alerj/parla#70]
esta imagem continua com a proporção diferente das demais

![image](https://user-images.githubusercontent.com/36640733/36740392-0e149d06-1bc1-11e8-9649-f29913900cf7.png)

**Comment by antonioribeiro** [comment]
A image agora está ok, mas as outras estão com proporção diferente. Esta aqui

![image](https://user-images.githubusercontent.com/3182864/36741769-b759bde4-1bc4-11e8-8f02-bdd4d7807276.png)

Quando reduzida pra 1200 de largura, fica com 801 de altura:

![image](https://user-images.githubusercontent.com/3182864/36741833-e13a089e-1bc4-11e8-8485-f288a9faa9a7.png)

Este 1 pixel pra quem é chato aparece muito na tela.

Assim, pra facilitar, talvez seja melhor vocês enviarem elas novamente dentro da proporção correta:

```
1070-materia-saude-carnaval-rafael-wallace-1200x800.jpg
1070-materia-saude-carnaval-rafael-wallace.jpg
antigo-restaurante-1200x800.jpg
antigo-restaurante.jpg
antonio-conceicao4_01_02_2018-thiago-lontra-1200x900.jpg
antonio-conceicao4_01_02_2018-thiago-lontra.jpg
daisa-conceicao.jpg
ex-africa-2-foto-alexandre-macieira-riotur-1200x800.jpg
ex-africa-2-foto-alexandre-macieira-riotur.jpg
ex-africa-3-foto-alexandre-macieira-riotur-1200x800.jpg
ex-africa-3-foto-alexandre-macieira-riotur.jpg
ex-africa-foto-alexandre-macieira-riotur-1200x800.jpg
ex-africa-foto-alexandre-macieira-riotur.jpg
gabriel-sorriso.jpg
gabriel-sorriso1_rafael-wallace-1200x800.jpg
gabriel-sorriso1_rafael-wallace.jpg
humano-papel-e-caneta.jpg
```

Lembrando que, as fotos que existirem em alta resolução, precisarão ter sua versão em baixa em outro arquivo, no tamanho 1200x800. Exemplo:

```
gabriel-sorriso1_rafael-wallace.jpg
gabriel-sorriso1_rafael-wallace-1200x800.jpg
```

**Comment by antonioribeiro** [comment]
Aquele pixel de diferença:

![image](https://user-images.githubusercontent.com/3182864/36742435-66dad824-1bc6-11e8-8b33-9cc1fc3addf1.png)

**Comment by brenot** [comment]
#onepixelmetters

**Comment by dtiriba** [comment]
![ex-africa-foto-alexandre-macieira-riotur-1200x800](https://user-images.githubusercontent.com/36640733/36742850-83626e7a-1bc7-11e8-9b6f-17237e7b0f9d.jpg)

foto atualizada

**Comment by antonioribeiro** [comment]
E as outras todas?

**Comment by antonioribeiro** [comment]
É melhor vocês enviarem todas novamente, pode ser?
Acertem as proporções de todas e enviem.

**Comment by antonioribeiro** [comment]
Quando fizermos a interface de upload, provavelmente vamos ter que negar fotos fora da proporção.

**Comment by brenot** [comment]
https://calculateaspectratio.com/

**Comment by dtiriba** [comment]
Vc consegue me mandar todas como estão no servidor? Assim eu abro tudo e ajusto de uma vez

**Comment by brenot** [comment]
Verifiquei aqui, e somente as dessa exposição da africa estão fora do padrão

**Comment by dtiriba** [comment]
Valeu, Breno. Não fui eu que editei. Do contrário, teria colocado tudo no padrão pelo photoshop

**Comment by brenot** [comment]
https://parla.antoniocarlosribeiro.com/images/photos/ex-africa-2-foto-alexandre-macieira-riotur.jpg
https://parla.antoniocarlosribeiro.com/images/photos/ex-africa-3-foto-alexandre-macieira-riotur.jpg

**Comment by dtiriba** [comment]
![ex-africa-3-foto-alexandre-macieira-riotur-1200x800](https://user-images.githubusercontent.com/36640733/36743476-26734822-1bc9-11e8-8663-9a4974090604.jpg)
![Uploading ex-africa-2-foto-alexandre-macieira-riotur-1200x800.jpg…]()
