### ISSUE TITLE
SGV da logo horizontal

### ISSUE THREAD

**Issue by dtiriba** [alerj/parla#74]
[Parla_horizontal.zip](https://github.com/alerj/parla/files/1772734/Parla_horizontal.zip)

**Comment by brenot** [comment]
@dtiriba substitui o logo que estava , por esse que você mandou ai, é isso que eu devia fazer? (esse sistema de gerenciamento de proj. que estamos usando, baseado em issues , é muito bom, mas para que ele funcione de maneira mais fluida é interessante que se explique bem cada tarefa, ou issue)

Fiquei na dúvida.

Outra observação, é sobre a nomenclatura dos arquivos, não devemos usar caixa alta no nome dos arquivos para evitar conflitos (o servidor é UNIX, e lida diferente com os nomes de arquivos).

**Comment by dtiriba** [comment]
Olá. A logo ainda não foi atualizada no Parla.
