### ISSUE TITLE
PARLA 1 - MATÉRIA 2

### ISSUE THREAD

**Issue by dtiriba** [alerj/parla#87]
# Exemplo de solidariedade através do esporte 

Autor: Márcia Manga
 
Ele sempre foi irrequieto, alto, e gostava de desafios. Por isso, não foi difícil perceber que aquele adolescente, então com 14 anos, tinha o biótipo e a personalidade ideais para as artes marciais. E foi a partir do convite desse amigo que Elton Moura, hoje com 34 anos, 1,80 m de altura, e 98 kg; entrou no mundo dos golpes, tatames, quimonos e faixas. E dele não saiu mais. “Na primeira aula já me identifiquei com o jiu-jitsu e, com dois meses de treino, já competia”, lembra Elton, cinegrafista da Assembleia Legislativa do Rio de Janeiro (Alerj). 
 
Na equipe “Gama Filho Serginho Jiu-Jitsu”, o menino começou a mudar de faixa e a colecionar medalhas. A rápida ascensão, no entanto, foi de encontro à necessidade de ajudar a mãe que, sozinha, criou quatro filhos. “Não pude me dedicar ao esporte como gostaria porque tenho três irmãos e tive que ajudar a minha mãe a sustentá-los”, explica.
 
Foi justamente a necessidade econômica que trouxe Elton, aos 21 anos, para a Alerj, onde começou como assistente de cinegrafista. “Nunca tinha pensado em trabalhar em TV, mas gostei”, lembra. Depois de duas passagens pela Casa, a última começou há dez anos, foi promovido a cinegrafista, casou e se tornou pai. Mas nunca esqueceu a antiga paixão pelo esporte.
 
Mesmo sem competir como no início, continuou treinando e trocando de faixas: branca, azul, roxa...e agora a marrom. Conquistas que o levaram, recentemente, a ser auxiliar do seu mestre Alexssandro Feitosa, durante os treinos.

No último ano, também passou a treinar mais pesado, emagreceu e se dedicou de tal forma que ganhou o Campeonato Copa Alfa. Vitória que acabou rendendo um convite. “A diretoria da equipe GF Team, após o campeonato, fez uma seleção para convocar uma equipe mundial master de jiu-jitsu (faixa marrom), em Miami, em junho, e fui selecionado”, comemora.
 
Se dependesse de vontade, a mala já estaria pronta, mas Elton foi obrigado a recusar o convite: “A escolha do meu nome é fruto de muita dedicação ao esporte durante esses anos, mas falta patrocínio. A viagem é cara e não tenho como bancar os custos”, lamenta.         
 
Como bom atleta, não deixou que essa frustração o paralisasse e, passou a pensar como poderia reverter o que aprendeu no esporte em benefício dos colegas de trabalho. Com o incentivo do apresentador do programa “Arena Esportiva" da TV Alerj, Rui Guilherme, começou a formatar um projeto para levar o jiu-jtsu para os funcionários da Casa. Rui lembra a importância da arte marcial para melhorar a relação interpessoal, a disciplina e a confraternização.
 
Juntos, Elton e Rui começaram a divulgar informalmente o projeto e já receberam o apoio de colegas. Ainda em busca de um nome para a ideia, o faixa-marrom ressalta o caráter sem fim lucrativo da iniciativa. Como o jiu-jitsu não utiliza armas e recorre mais à técnica do que à força, esta arte marcial tornou-se ideal como defesa pessoal. Característica que levou a subdiretora-geral de Segurança, Cristina de Vilhena Castro, a engrossar a fila dos que esperam que as aulas de jiu-jitsu venham logo e para ficar. “O jiu-jitsu é adequado para o perfil da segurança da Casa porque temos que ter uma pronta defesa contra um agressor ou invasor”, ressalta Cristina.

**Comment by dtiriba** [comment]
![eltonmoura2-thiagolontra_22_05_18_parla](https://user-images.githubusercontent.com/36640733/41438861-256bb448-6fff-11e8-880a-a22a20594438.jpg)

Foto principal. 
Legenda: Elton Moura é cinegrafista da TV Alerj e tem no jiu jitsu sua grande paixão (Foto: Thiago Lontra)

**Comment by dtiriba** [comment]
![elton moura - jiujiteiro_parla_350px](https://user-images.githubusercontent.com/36640733/41439123-ea337234-6fff-11e8-92ed-f380b709c037.jpg)

Essa aqui pode entrar no corpo da matéria, alinhada à esquerda?

**Comment by antonioribeiro** [comment]
@dtiriba você não tem essas fotos em alta? Elas estão todas abaixo de 1200x800

**Comment by antonioribeiro** [comment]
@dtiriba, vou falar só aqui, mas preciso em todas as matérias:

- titulo
- ordem
- categoria (ainda não estamos usando mas é já criar)
- subtitulo
- lead
- texto
- destaque (sim/nao)
- fotos
- autores
- tags (é usado quando abrimos a matéria)

**Comment by antonioribeiro** [comment]
Segue o padrão pra preenchimento, pode copiar e colar isso sempre de uma materia pra outra:

#### titulo
(aqui)
#### ordem
(aqui)
#### categoria 
(aqui) - (ainda não estamos usando mas é já criar)
#### subtitulo
(aqui)
#### lead
(aqui)
#### texto
(aqui)
#### destaque (sim/nao)
(aqui)
#### fotos
(nomear todas aqui aqui)
padrão de nome:
```
(nome_da_pessoa_ou_lugar)(situacao)(por_fotografo)(2,3,4, se tiver mais de uma).extensao
```
exemplos:
```
elton_moura_na_camera_por_thiago_lontra.jpg
#### autores
(aqui)
#### tags (é usado quando abrimos a matéria)
(separadas por vírgula, todas em minúsculas)

**Comment by antonioribeiro** [comment]
Segue o padrão pra preenchimento, pode copiar e colar isso sempre de uma materia pra outra:

## titulo
(aqui)
## ordem
(aqui)
## categoria 
(aqui) - (ainda não estamos usando mas é já criar)
## subtitulo
(aqui)
## lead
(aqui)
## texto
(aqui)
## destaque (sim/nao)
(aqui)
## fotos
(nomear todas aqui aqui)
padrão de nome:
```
(nome_da_pessoa_ou_lugar)(situacao)(por_fotografo)(2,3,4, se tiver mais de uma).extensao
```
exemplos:
```
elton_moura_na_camera_por_thiago_lontra.jpg
elton_moura_na_camera_por_thiago_lontra2.jpg
palacio_tiradentes_plenario_por_rafael_wallace.jpg
```
## autores
(aqui)
## tags (é usado quando abrimos a matéria)
(separadas por vírgula, todas em minúsculas)

**Comment by dtiriba** [comment]
titulo
Exemplo de solidariedade através do esporte

ordem
2

categoria / editoria
perfil

subtitulo
POR ORA, NÃO TERÁ

lead
Ele sempre foi irrequieto, alto, e gostava de desafios. Por isso, não foi difícil perceber que aquele adolescente, então com 14 anos, tinha o biótipo e a personalidade ideais para as artes marciais. E foi a partir do convite desse amigo que Elton Moura, hoje com 34 anos, 1,80 m de altura, e 98 kg; entrou no mundo dos golpes, tatames, quimonos e faixas. E dele não saiu mais. “Na primeira aula já me identifiquei com o jiu-jitsu e, com dois meses de treino, já competia”, lembra Elton, cinegrafista da Assembleia Legislativa do Rio de Janeiro (Alerj).

texto
Na equipe “Gama Filho Serginho Jiu-Jitsu”, o menino começou a mudar de faixa e a colecionar medalhas. A rápida ascensão, no entanto, foi de encontro à necessidade de ajudar a mãe que, sozinha, criou quatro filhos. “Não pude me dedicar ao esporte como gostaria porque tenho três irmãos e tive que ajudar a minha mãe a sustentá-los”, explica.

Foi justamente a necessidade econômica que trouxe Elton, aos 21 anos, para a Alerj, onde começou como assistente de cinegrafista. “Nunca tinha pensado em trabalhar em TV, mas gostei”, lembra. Depois de duas passagens pela Casa, a última começou há dez anos, foi promovido a cinegrafista, casou e se tornou pai. Mas nunca esqueceu a antiga paixão pelo esporte.

Mesmo sem competir como no início, continuou treinando e trocando de faixas: branca, azul, roxa...e agora a marrom. Conquistas que o levaram, recentemente, a ser auxiliar do seu mestre Alexssandro Feitosa, durante os treinos.

No último ano, também passou a treinar mais pesado, emagreceu e se dedicou de tal forma que ganhou o Campeonato Copa Alfa. Vitória que acabou rendendo um convite. “A diretoria da equipe GF Team, após o campeonato, fez uma seleção para convocar uma equipe mundial master de jiu-jitsu (faixa marrom), em Miami, em junho, e fui selecionado”, comemora.

Se dependesse de vontade, a mala já estaria pronta, mas Elton foi obrigado a recusar o convite: “A escolha do meu nome é fruto de muita dedicação ao esporte durante esses anos, mas falta patrocínio. A viagem é cara e não tenho como bancar os custos”, lamenta.

Como bom atleta, não deixou que essa frustração o paralisasse e, passou a pensar como poderia reverter o que aprendeu no esporte em benefício dos colegas de trabalho. Com o incentivo do apresentador do programa “Arena Esportiva" da TV Alerj, Rui Guilherme, começou a formatar um projeto para levar o jiu-jtsu para os funcionários da Casa. Rui lembra a importância da arte marcial para melhorar a relação interpessoal, a disciplina e a confraternização.

Juntos, Elton e Rui começaram a divulgar informalmente o projeto e já receberam o apoio de colegas. Ainda em busca de um nome para a ideia, o faixa-marrom ressalta o caráter sem fim lucrativo da iniciativa. Como o jiu-jitsu não utiliza armas e recorre mais à técnica do que à força, esta arte marcial tornou-se ideal como defesa pessoal. Característica que levou a subdiretora-geral de Segurança, Cristina de Vilhena Castro, a engrossar a fila dos que esperam que as aulas de jiu-jitsu venham logo e para ficar. “O jiu-jitsu é adequado para o perfil da segurança da Casa porque temos que ter uma pronta defesa contra um agressor ou invasor”, ressalta Cristina.

fotos
elton_moura_por_Thiago_Lontra.jpg

autores
Márcia Manga

tags 
perfil, jiu jitsu, esporte, tv alerj, personagem

**Comment by dtiriba** [comment]
A foto dele de quimono não entrou. Ela pode entrar pequena, alinhada à esquerda, mesmo sem lightbox?

**Comment by dtiriba** [comment]
Vi que a foto entrou, mas o texto pode correr ao lado da imagem?

valeu!

**Comment by antonioribeiro** [comment]
Temos limitações ainda, o Markdown não nos deixa fazer algumas coisas, vamos pensar o que fazer neste caso

**Comment by dtiriba** [comment]
Tranquilo. Se não der, talvez seja melhor deixar no final com lightbox, como vcs tinham feito na matéria do Parla Piloto

**Comment by brenot** [comment]
@dtiriba Estamos estudando a melhor maneira de resolver essa questão, entretanto, seria interessante nesses casos voce especificar em que ponto do texto entra a foto..

**Comment by dtiriba** [comment]
Sim, farei isso no futuro! Abs

**Comment by dtiriba** [comment]
Novo título: 

Solidariedade através do esporte
