### ISSUE TITLE
PARLA 1 - Matéria 3

### ISSUE THREAD

**Issue by dtiriba** [alerj/parla#88]
# Sindalerj: associado extra-quadro número um

Autor: Symone Munay

O assistente parlamentar Rafael Ribeiro Riccio, 30 anos, foi o primeiro servidor extra-quadro a se cadastrar no Sindicato dos Servidores da Alerj - Sindalerj, no início deste ano, depois da alteração do estatuto da entidade e da campanha interna visando às novas filiações. Com a mudança, os funcionários comissionados ou requisitados já podem se filiar ao Sindalerj. Com uma contribuição mensal de R$ 35, o sindicato oferece convênios e diversos serviços aos seus novos associados, assim como aos 700 servidores ativos e aposentados e a seus familiares.
  
 "Trabalho na Casa há 12 anos, sempre tive contato com os representantes do sindicato, acompanhei de perto várias lutas e conquistas. Assim que tive a oportunidade de me vincular à instituição, não perdi tempo. Foi assim que me tornei o extra-quadro número um do Sindalerj", disse Riccio, que ingressou na Alerj como estagiário e hoje trabalha no protocolo do Plenário, setor ligado à Secretaria da Mesa Diretora. Ele é  responsável pelo recebimento dos projetos de lei, emendas e projetos de resoluções dos parlamentares.
 
Segundo o presidente do sindicato, Nelson Braga Moreno, a adesão dos comissionados ainda está tímida, mas ele espera alcançar resultados positivos quando todos tiverem acesso à pauta de reivindicações para 2018/2019. A realização de um concurso público para os diversos setores da Casa faz parte da lista. "Somos poucos servidores na ativa e muitos às vésperas da aposentadoria. Precisamos renovar nossos quadros", disse Moreno, que enumerou como prioridades o ajuste no auxílio-alimentação (já concedido);  a criação do auxílio-saúde e o novo plano de cargos e salários.

"Lutamos por todos, seja estatutário ou não. O importante é que aqueles que trabalham na Alerj sejam comissionados ou requisitados, se sintam representados dentro das normas legais. Ser sindicalizado é se fazer ouvir",  destacou o presidente.

 

**Filiação e benefícios**

O cadastro deve ser feito através do preenchimento de uma ficha de inscrição na sede do sindicato, na Travessa do Paço, 23 - Sala 205, Centro, ao lado do Palácio Tiradentes. Mais informações podem ser obtidas pelo telefones 2253-0435 e 2203-0415 ou pelo e-mail: [sindalerj@sindalerj.com.br](mailto:sindalerj@sindalerj.com.br). 

Os associados do Sindalerj contam com os benefícios exclusivos por meio das parcerias com planos de saúde, faculdades, restaurantes, farmácias e agências de viagem. Dispõem também de assistência jurídica e serviço contábil.

**Comment by dtiriba** [comment]
![parla_rafaelribeiro_octaciliobarbosa_14_06_18_parla](https://user-images.githubusercontent.com/36640733/41440149-e0ab3c7a-7003-11e8-9ca5-9d0d64b09d58.jpg)

Legenda: Rafael Riccio trabalha na Alerj há 12 anos e desde o início deste ano integra o Sindalerj (Foto: Octacílio Barbosa)

**Comment by dtiriba** [comment]
- O link para o email não entrou. Ficou assim: e-mail: (nome)[mailto:sindalerj@sindalerj.com.br].

- Favor colocar link para mapa no trecho
Travessa do Paço, 23 - Sala 205
 https://goo.gl/maps/6EW68gb3cSB2

**Comment by antonioribeiro** [comment]
Feito

**Comment by antonioribeiro** [comment]
Podemos fechar esta?

**Comment by dtiriba** [comment]
SIM!
